#!/usr/bin/env python3
"""
G4.6 -- single source of truth for the CUTLASS config sweep.

Regenerates csrc/g4_6_cutlass_cfg??.cu (one instantiation per translation unit)
and rewrites the kCfg table inside csrc/g4_6_cutlass_gemm.cpp between the
BEGIN/END markers, so the two can never drift.  CPU-only; run it directly, it
never touches the GPU.

    python3 probes/g4_6_gen_cfgs.py

Round 1 = cfg 0-13 (job 101): tiles seeded from step 37's winning hand-written
cfg[11] (BM=128,BN=128,BK=64,stages=2), plus FP32-accumulate twins for the A/B.
Round 2 = cfg 14-23: neighbours of round 1's winners (cfg[6] at qkv/large_batch,
cfg[5] at out_proj/large_batch) plus the threadblock-swizzle lever, run to
establish whether the 71.4%-of-tier result is a saturation point or a first
sample.

Shared-memory budget, 2-byte operands, Ada's 101376 B/block opt-in cap:
    bytes/stage = (BM*BK + BN*BK) * 2
so BK=64 TB128x128 -> 32768/stage (3 stages max), BK=32 TB128x256 -> 24576/stage
(4 stages max), TB256x256 BK=32 -> 32768/stage (3 stages max).
"""
import os

H = "cutlass::half_t"
F = "float"

# (idx, ElementAccumulator, BM, BN, BK, WM, WN, WK, stages, swizzle)
CFGS = [
    # ---- round 1: seeded from step 37's cfg[11], + FP32-accum twins --------
    (0,  H, 128, 128, 64, 64, 64, 64, 3, 1),
    (1,  H, 128, 128, 64, 64, 64, 64, 2, 1),   # direct cfg[11] analogue
    (2,  H, 128, 128, 32, 64, 64, 32, 4, 1),
    (3,  H, 128, 128, 32, 64, 64, 32, 6, 1),
    (4,  H, 128, 256, 64, 64, 64, 64, 2, 1),
    (5,  H, 256, 128, 64, 64, 64, 64, 2, 1),
    (6,  H, 128, 256, 32, 64, 64, 32, 4, 1),
    (7,  H, 256, 128, 32, 64, 64, 32, 4, 1),
    (8,  H, 128,  64, 64, 64, 32, 64, 4, 1),
    (9,  H,  64, 128, 64, 32, 64, 64, 4, 1),
    (10, F, 128, 128, 64, 64, 64, 64, 3, 1),   # twin of 0
    (11, F, 128, 128, 64, 64, 64, 64, 2, 1),   # twin of 1
    (12, F, 128, 128, 32, 64, 64, 32, 4, 1),   # twin of 2
    (13, F, 128, 256, 64, 64, 64, 64, 2, 1),   # twin of 4
    # ---- round 2: neighbours of the round-1 winners + the swizzle lever ----
    (14, H, 128, 256, 32, 64, 64, 32, 4, 4),   # cfg[6] + swizzle 4
    (15, H, 128, 256, 32, 64, 64, 32, 4, 8),   # cfg[6] + swizzle 8
    (16, H, 256, 128, 32, 64, 64, 32, 4, 4),   # cfg[7] + swizzle 4
    (17, H, 128, 256, 32, 64, 64, 32, 3, 1),   # cfg[6], shallower pipeline
    (18, H, 128, 256, 32, 64, 64, 32, 2, 1),
    (19, H, 256, 256, 32, 64, 64, 32, 3, 1),   # 16 warps, 96 KB
    (20, H,  64, 256, 64, 32, 64, 64, 2, 1),
    (21, H, 128, 256, 64, 64, 64, 64, 2, 4),   # cfg[4] + swizzle 4
    (22, H, 256, 128, 64, 64, 64, 64, 2, 4),   # cfg[5] + swizzle 4
    (23, H, 128, 128, 64, 64, 64, 64, 3, 4),   # cfg[0] + swizzle 4
]

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BEGIN = "// ---- BEGIN GENERATED kCfg (probes/g4_6_gen_cfgs.py) ----"
END = "// ---- END GENERATED kCfg ----"


def main():
    for (i, acc, bm, bn, bk, wm, wn, wk, stg, swz) in CFGS:
        tag = "accF16" if acc == H else "accF32"
        stage_bytes = (bm * bk + bn * bk) * 2
        body = (
            "// G4.6 -- one CUTLASS instantiation, one translation unit.\n"
            "// GENERATED by probes/g4_6_gen_cfgs.py; do not hand-edit.\n"
            '#include "g4_6_cutlass_gemm.cuh"\n\n'
            f"// cfg[{i}] {tag} TB {bm}x{bn}x{bk} warp {wm}x{wn}x{wk} "
            f"stages {stg} swizzle {swz}\n"
            f"//   mainloop smem = {stg} x {stage_bytes} B = "
            f"{stg * stage_bytes} B (Ada cap 101376 B)\n"
            f"G46_DEFINE({i}, {acc}, {bm}, {bn}, {bk}, {wm}, {wn}, {wk}, "
            f"{stg}, {swz})\n")
        with open(os.path.join(ROOT, "csrc",
                               f"g4_6_cutlass_cfg{i:02d}.cu"), "w") as fh:
            fh.write(body)

    rows = []
    for (i, acc, bm, bn, bk, wm, wn, wk, stg, swz) in CFGS:
        rows.append(f"    {{g46_launch_{i}, {bm}, {bn}, {bk}, {wm}, {wn}, "
                    f"{wk}, {stg}, {swz}, {0 if acc == H else 1}}},")
    decls = "\n".join(
        "DECL(%d)" % i for (i, *_rest) in CFGS)
    table = (BEGIN + "\n" + decls + "\n#undef DECL\n\n"
             "namespace {\nstruct CfgDesc {\n  LaunchFn fn;\n"
             "  int BM, BN, BK, WM, WN, WK, STG, SWZ, ACCF32;\n};\n"
             "const CfgDesc kCfg[] = {\n" + "\n".join(rows) +
             "\n};\nconstexpr int kNumCfg = "
             "(int)(sizeof(kCfg) / sizeof(kCfg[0]));\n}  // namespace\n" + END)

    cpp_path = os.path.join(ROOT, "csrc", "g4_6_cutlass_gemm.cpp")
    src = open(cpp_path).read()
    a = src.index(BEGIN)
    b = src.index(END) + len(END)
    open(cpp_path, "w").write(src[:a] + table + src[b:])
    print(f"generated {len(CFGS)} TUs and rewrote kCfg in {cpp_path}")


if __name__ == "__main__":
    main()
