#!/usr/bin/env python3
"""
Keep torch_transformer_benchmark.py equal to (judges' canonical harness + our
model), and re-splice it onto a fresh canonical when the judges publish one.

torch_transformer_benchmark.py is now the SINGLE source of truth -- benchmark.py
was removed once the safety net moved here. The splice is SELF-HOSTING: our
contribution is delimited in the file by `>>> BEGIN user ... >>>` sentinels, so
this reads our model out of the shipped file, drops it into a clean copy of
~/torch_transformer_benchmark.py, and writes the result back to the same path.

    python3 tools/sync_entrypoint.py            # re-splice onto the canonical
    python3 tools/sync_entrypoint.py --check    # exit 1 if the file is not
                                                # exactly canonical + our model

`--check` is the real invariant: it proves nothing outside the sentinels has
drifted from the judges' harness. tools/verify_baseline.py is the AST-level
version of the same guarantee over the 20 frozen symbols.

"""
import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OURS = os.path.join(ROOT, "torch_transformer_benchmark.py")
CANON = os.path.expanduser("~/torch_transformer_benchmark.py")
OUT = os.path.join(ROOT, "torch_transformer_benchmark.py")

HEADER = (
    "# TikTok TechJam - Problem 3 submission entry point.\n"
    "#\n"
    "# This is the official torch_transformer_benchmark.py with "
    "UserOptimizedTransformer\n"
    "# (and its module-level helpers) implemented in place of the stub. It is "
    "the\n"
    "# SINGLE source of truth - edit it directly.\n"
    "#\n"
    "# The scoring half - BaselineTransformer, compare_outputs, "
    "run_accuracy_tests,\n"
    "# benchmark_models, parse_args, main - is byte-for-byte the reference "
    "harness.\n"
    "# DO NOT EDIT ANYTHING OUTSIDE THE `>>> BEGIN user ... >>>` SENTINELS "
    "BELOW:\n"
    "# tools/verify_baseline.py diffs all 20 frozen symbols against the "
    "judges'\n"
    "# ~/torch_transformer_benchmark.py at AST level and fails the build on "
    "any\n"
    "# divergence.\n"
    "#\n"
    "#   python3 torch_transformer_benchmark.py --causal --batch-size <B> "
    "--seq-len <S> \\\n"
    "#       --d-model <d> --heads <H> --layers <L> --ffn-dim <F>\n"
    "#\n"
    "# tools/sync_entrypoint.py re-splices the sentinel blocks onto a fresh "
    "copy of\n"
    "# the canonical harness - run it if the judges publish an updated "
    "harness.\n\n"
)


# Sentinels delimiting OUR contribution inside the generated file. They make
# the splice self-hosting: benchmark.py is gone, so the shipped file is itself
# the source to re-splice onto an updated canonical harness. Without them the
# extractor keys off `class TransformerConfig`, which in the shipped layout sits
# AHEAD of our helpers (it comes from the canonical head), so the helper block
# would be silently dropped -- measured, not assumed.
H_BEG = "# >>> BEGIN user helpers -- generated by tools/sync_entrypoint.py >>>\n"
H_END = "# <<< END user helpers <<<\n"
M_BEG = "# >>> BEGIN user model -- generated by tools/sync_entrypoint.py >>>\n"
M_END = "# <<< END user model <<<\n"


def _between(lines, beg, end):
    """Lines strictly between two sentinel lines, or None if absent."""
    try:
        i = lines.index(beg)
        j = lines.index(end)
    except ValueError:
        return None
    return lines[i + 1:j]


def _idx(lines, prefix, start=0):
    for i in range(start, len(lines)):
        if lines[i].startswith(prefix):
            return i
    raise SystemExit(f"sync_entrypoint: marker not found: {prefix!r}")


def build() -> str:
    ours = open(OURS).read().splitlines(keepends=True)
    canon = open(CANON).read().splitlines(keepends=True)

    # --- our module-level helpers ------------------------------------------
    hlines = _between(ours, H_BEG, H_END)
    if hlines is None:
        # un-sentinelled source (the original benchmate layout): everything
        # between the last import and class TransformerConfig
        o_imp = _idx(ours, "import torch.nn.functional as F")
        o_cfg = _idx(ours, "class TransformerConfig")
        hlines = ours[o_imp + 1:o_cfg]
        # drop the decorator/blank lines that belong to `class TransformerConfig`
        # (which itself comes from the canonical harness, not from us)
        while hlines and (hlines[-1].strip() == ""
                          or hlines[-1].lstrip().startswith("@")):
            hlines.pop()
    helpers = "".join(hlines).strip("\n") + "\n"

    # --- our optimized model ------------------------------------------------
    mlines = _between(ours, M_BEG, M_END)
    if mlines is None:
        o_cls = _idx(ours, "class UserOptimizedTransformer")
        o_end = _idx(ours, "def copy_model_weights", o_cls)
        mlines = ours[o_cls:o_end]
    model = "".join(mlines).strip("\n") + "\n"

    # --- canonical harness, with our block replacing its stub class --------
    c_cls = _idx(canon, "class UserOptimizedTransformer")
    c_end = _idx(canon, "def copy_model_weights", c_cls)
    head = canon[:c_cls]
    tail = canon[c_end:]

    # our helpers use os.environ; the canonical imports do not include os
    for i, ln in enumerate(head):
        if ln.startswith("import math"):
            if not any(x.startswith("import os") for x in head):
                head.insert(i + 1, "import os\n")
            break

    body = (
        "".join(head).rstrip("\n")
        + "\n\n\n" + H_BEG + helpers + H_END
        + "\n\n" + M_BEG + model + M_END
        + "\n\n\n" + "".join(tail).lstrip("\n")
    )
    # keep a shebang on line 1 if the canonical had one; header goes under it
    if body.startswith("#!"):
        nl = body.index("\n") + 1
        return body[:nl] + HEADER + body[nl:]
    return HEADER + body


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if torch_transformer_benchmark.py is stale")
    a = ap.parse_args()

    if not os.path.exists(CANON):
        print(f"sync_entrypoint: canonical not found: {CANON}")
        return 1

    new = build()
    try:
        import ast
        ast.parse(new)
    except SyntaxError as e:
        print(f"sync_entrypoint: generated file does not parse: {e}")
        return 1

    if a.check:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != new:
            print("sync_entrypoint: torch_transformer_benchmark.py is STALE "
                  "-- run `python3 tools/sync_entrypoint.py`")
            return 1
        print("sync_entrypoint: torch_transformer_benchmark.py is up to date")
        return 0

    open(OUT, "w").write(new)
    n = new.count("\n")
    print(f"sync_entrypoint: wrote {OUT} ({n} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
