// G4.6 -- one CUTLASS instantiation, one translation unit.
// GENERATED by probes/g4_6_gen_cfgs.py; do not hand-edit.
#include "g4_6_cutlass_gemm.cuh"

// cfg[22] accF16 TB 256x128x64 warp 64x64x64 stages 2 swizzle 4
//   mainloop smem = 2 x 49152 B = 98304 B (Ada cap 101376 B)
G46_DEFINE(22, cutlass::half_t, 256, 128, 64, 64, 64, 64, 2, 4)
