// G4.6 -- one CUTLASS instantiation, one translation unit.
// GENERATED by probes/g4_6_gen_cfgs.py; do not hand-edit.
#include "g4_6_cutlass_gemm.cuh"

// cfg[18] accF16 TB 128x256x32 warp 64x64x32 stages 2 swizzle 1
//   mainloop smem = 2 x 24576 B = 49152 B (Ada cap 101376 B)
G46_DEFINE(18, cutlass::half_t, 128, 256, 32, 64, 64, 32, 2, 1)
