// G4.6 -- one CUTLASS instantiation, one translation unit.
// GENERATED by experiments/g4_6_gen_cfgs.py; do not hand-edit.
#include "g4_6_cutlass_gemm.cuh"

// cfg[26] accF16 TB 64x128x64 warp 32x64x64 stages 4 swizzle 1 splitk 2
//   mainloop smem = 4 x 24576 B = 98304 B (Ada cap 101376 B)
G46_DEFINE_SK(26, cutlass::half_t, 64, 128, 64, 32, 64, 64, 4, 1, 2)
