// G4.6 -- one CUTLASS instantiation, one translation unit.
// GENERATED by experiments/g4_6_gen_cfgs.py; do not hand-edit.
#include "g4_6_cutlass_gemm.cuh"

// cfg[3] accF16 TB 128x128x32 warp 64x64x32 stages 6 swizzle 1 splitk 1
//   mainloop smem = 6 x 16384 B = 98304 B (Ada cap 101376 B)
G46_DEFINE_SK(3, cutlass::half_t, 128, 128, 32, 64, 64, 32, 6, 1, 1)
