// G4.6 -- one CUTLASS instantiation, one translation unit.
// GENERATED by probes/g4_6_gen_cfgs.py; do not hand-edit.
#include "g4_6_cutlass_gemm.cuh"

// cfg[10] accF32 TB 128x128x64 warp 64x64x64 stages 3 swizzle 1
//   mainloop smem = 3 x 32768 B = 98304 B (Ada cap 101376 B)
G46_DEFINE(10, float, 128, 128, 64, 64, 64, 64, 3, 1)
