// G4.6 -- one CUTLASS instantiation, one translation unit.
// GENERATED by probes/g4_6_gen_cfgs.py; do not hand-edit.
#include "g4_6_cutlass_gemm.cuh"

// cfg[19] accF16 TB 256x256x32 warp 64x64x32 stages 3 swizzle 1
//   mainloop smem = 3 x 32768 B = 98304 B (Ada cap 101376 B)
G46_DEFINE(19, cutlass::half_t, 256, 256, 32, 64, 64, 32, 3, 1)
