// G4.6 -- one CUTLASS instantiation, one translation unit.
// GENERATED by experiments/g4_6_gen_cfgs.py; do not hand-edit.
#include "g4_6_cutlass_gemm.cuh"

// cfg[20] accF16 TB 64x256x64 warp 32x64x64 stages 2 swizzle 1 splitk 1
//   mainloop smem = 2 x 40960 B = 81920 B (Ada cap 101376 B)
G46_DEFINE_SK(20, cutlass::half_t, 64, 256, 64, 32, 64, 64, 2, 1, 1)
