// G4.6 -- one CUTLASS instantiation, one translation unit.
// GENERATED by probes/g4_6_gen_cfgs.py; do not hand-edit.
#include "g4_6_cutlass_gemm.cuh"

// cfg[8] accF16 TB 128x64x64 warp 64x32x64 stages 4 swizzle 1
//   mainloop smem = 4 x 24576 B = 98304 B (Ada cap 101376 B)
G46_DEFINE(8, cutlass::half_t, 128, 64, 64, 64, 32, 64, 4, 1)
