// G4.6 -- one CUTLASS instantiation, one translation unit.
// GENERATED by experiments/g4_6_gen_cfgs.py; do not hand-edit.
#include "g4_6_cutlass_gemm.cuh"

// cfg[27] accF16 TB 128x256x32 warp 64x64x32 stages 4 swizzle 1 splitk 2
//   mainloop smem = 4 x 24576 B = 98304 B (Ada cap 101376 B)
G46_DEFINE_SK(27, cutlass::half_t, 128, 256, 32, 64, 64, 32, 4, 1, 2)
