// G4.6 -- one CUTLASS instantiation, one translation unit.
// GENERATED by experiments/g4_6_gen_cfgs.py; do not hand-edit.
#include "g4_6_cutlass_gemm.cuh"

// cfg[13] accF32 TB 128x256x64 warp 64x64x64 stages 2 swizzle 1 splitk 1
//   mainloop smem = 2 x 49152 B = 98304 B (Ada cap 101376 B)
G46_DEFINE_SK(13, float, 128, 256, 64, 64, 64, 64, 2, 1, 1)
