// G4.6 -- one CUTLASS instantiation, one translation unit.
// GENERATED by probes/g4_6_gen_cfgs.py; do not hand-edit.
#include "g4_6_cutlass_gemm.cuh"

// cfg[1] accF16 TB 128x128x64 warp 64x64x64 stages 2 swizzle 1
//   mainloop smem = 2 x 32768 B = 65536 B (Ada cap 101376 B)
G46_DEFINE(1, cutlass::half_t, 128, 128, 64, 64, 64, 64, 2, 1)
